In [1]:
import pip

In [2]:
for pkg in ['mxnet', 'mxnet-cu75', 'mxnet-cu80']:
    pip.main(['show', pkg])

Name: mxnet
Version: 1.1.0
Summary: MXNet is an ultra-scalable deep learning framework. This version uses openblas.
Home-page: https://github.com/apache/incubator-mxnet
Author: UNKNOWN
Author-email: UNKNOWN
License: Apache 2.0
Location: /Users/poodarchu/anaconda3/lib/python3.6/site-packages
Requires: graphviz, requests, numpy


In [3]:
from mxnet import nd
x = nd.ones(3)
x.context

cpu(0)

In [5]:
import mxnet as mx
a = nd.array([1, 2, 3], ctx=mx.gpu())

MXNetError: [13:08:27] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010b3252cf libmxnet.so + 58063
[bt] (1) 1   libmxnet.so                         0x000000010b32506f libmxnet.so + 57455
[bt] (2) 2   libmxnet.so                         0x000000010b324979 libmxnet.so + 55673
[bt] (3) 3   libmxnet.so                         0x000000010c60c5ec MXNDListFree + 3436044
[bt] (4) 4   libmxnet.so                         0x000000010c60a4df MXNDListFree + 3427583
[bt] (5) 5   libmxnet.so                         0x000000010baece06 libmxnet.so + 8216070
[bt] (6) 6   libmxnet.so                         0x000000010baecb23 libmxnet.so + 8215331
[bt] (7) 7   libmxnet.so                         0x000000010baec891 libmxnet.so + 8214673
[bt] (8) 8   libmxnet.so                         0x000000010c294471 MXNDArrayCreateEx + 465
[bt] (9) 9   libffi.6.dylib                      0x00000001081d8884 ffi_call_unix64 + 76



In [6]:
b = nd.zeros((3,2), ctx=mx.gpu())
c = nd.random.uniform(shape=(2, 3), ctx=mx.gpu())

MXNetError: [13:09:14] src/imperative/imperative.cc:78: Operator _zeros is not implemented for GPU.

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x000000010b3252cf libmxnet.so + 58063
[bt] (1) 1   libmxnet.so                         0x000000010b32506f libmxnet.so + 57455
[bt] (2) 2   libmxnet.so                         0x000000010c326f34 MXNDListFree + 399188
[bt] (3) 3   libmxnet.so                         0x000000010c32b07a MXNDListFree + 415898
[bt] (4) 4   libmxnet.so                         0x000000010c2ad277 MXCustomFunctionRecord + 16119
[bt] (5) 5   libmxnet.so                         0x000000010c2ae444 MXImperativeInvokeEx + 164
[bt] (6) 6   libffi.6.dylib                      0x00000001081d8884 ffi_call_unix64 + 76



In [9]:
# 如果 源和目标的 context 相同，as_in_context 不复制，直接将引用指向，而 copyto 总是新建内存
y = x.copyto(mx.cpu())
z = x.as_in_context(mx.cpu())

In [10]:
y, z

(
 [ 1.  1.  1.]
 <NDArray 3 @cpu(0)>, 
 [ 1.  1.  1.]
 <NDArray 3 @cpu(0)>)

In [11]:
# 计算会在数据的 context 上执行
# 计算要求数据在同一个设备上

In [12]:
# 如果某个操作需要将 NDArray 中的内容转出来，例如打印成 numpy 格式，如果需要的话，系统都会自动将数据 copy 到主存
print(y)
print(y.asnumpy())
print(y.sum().asscalar())


[ 1.  1.  1.]
<NDArray 3 @cpu(0)>
[ 1.  1.  1.]
3.0


In [13]:
from mxnet import gluon

In [15]:
net = gluon.nn.Sequential()
net.add(gluon.nn.Dense(1))

net.initialize(ctx=mx.cpu())