In [1]:
from mxnet.gluon import nn
from mxnet import nd

In [2]:
def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(4, activation="relu"))
        net.add(nn.Dense(2))
    return net

x = nd.random.uniform(shape=(3,5))

In [3]:
import sys
try:
    net = get_net()
    net(x)
except RuntimeError as err:
    sys.stderr.write(str(err))

Parameter sequential0_dense0_weight has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks

In [4]:
net.initialize()
net(x)


[[ 0.00212593  0.00365805]
 [ 0.00161272  0.00441845]
 [ 0.00204872  0.00352518]]
<NDArray 3x2 @cpu(0)>

In [5]:
print(net)

Sequential(
  (0): Dense(5 -> 4, Activation(relu))
  (1): Dense(4 -> 2, linear)
)


In [6]:
net[0]

Dense(5 -> 4, Activation(relu))

In [7]:
print(type(net))

<class 'mxnet.gluon.nn.basic_layers.Sequential'>


In [9]:
net[1]

Dense(4 -> 2, linear)

In [10]:
net.collect_params()

sequential0_ (
  Parameter sequential0_dense0_weight (shape=(4, 5), dtype=<class 'numpy.float32'>)
  Parameter sequential0_dense0_bias (shape=(4,), dtype=<class 'numpy.float32'>)
  Parameter sequential0_dense1_weight (shape=(2, 4), dtype=<class 'numpy.float32'>)
  Parameter sequential0_dense1_bias (shape=(2,), dtype=<class 'numpy.float32'>)
)

In [12]:
net[0].weight.data()


[[-0.06206018  0.06491279 -0.03182812 -0.01631819 -0.00312688]
 [ 0.0408415   0.04370362  0.00404529 -0.0028032   0.00952624]
 [-0.01501013  0.05958354  0.04705103 -0.06005495 -0.02276454]
 [-0.0578019   0.02074406 -0.06716943 -0.01844618  0.04656678]]
<NDArray 4x5 @cpu(0)>

In [13]:
net[0].weight.grad()


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
<NDArray 4x5 @cpu(0)>

In [14]:
params = net.collect_params()
params['sequential0_dense0_weight'].data()


[[-0.06206018  0.06491279 -0.03182812 -0.01631819 -0.00312688]
 [ 0.0408415   0.04370362  0.00404529 -0.0028032   0.00952624]
 [-0.01501013  0.05958354  0.04705103 -0.06005495 -0.02276454]
 [-0.0578019   0.02074406 -0.06716943 -0.01844618  0.04656678]]
<NDArray 4x5 @cpu(0)>

In [15]:
from mxnet import init

In [16]:
params.initialize(init=init.Normal(sigma=0.02), force_reinit=True)
print(net[0].weight.data(), net[0].bias.data())


[[ 0.02804598  0.00220872  0.00701151  0.02721515  0.00500832]
 [ 0.00112992  0.03227538 -0.01813176 -0.00385197 -0.01286032]
 [ 0.03360647 -0.02855298 -0.03083278 -0.02110904 -0.02623654]
 [-0.00293494  0.01282986 -0.01476417  0.04062728  0.01186534]]
<NDArray 4x5 @cpu(0)> 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>


In [17]:
# 延后的初始化
# 真正的初始化发生在看到数据时
net1 = get_net()
net1.collect_params()

sequential1_ (
  Parameter sequential1_dense0_weight (shape=(4, 0), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense0_bias (shape=(4,), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_weight (shape=(2, 0), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_bias (shape=(2,), dtype=<class 'numpy.float32'>)
)

In [18]:
net1.initialize()
net1.collect_params()

sequential1_ (
  Parameter sequential1_dense0_weight (shape=(4, 0), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense0_bias (shape=(4,), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_weight (shape=(2, 0), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_bias (shape=(2,), dtype=<class 'numpy.float32'>)
)

In [19]:
net1(x)
net1.collect_params()

sequential1_ (
  Parameter sequential1_dense0_weight (shape=(4, 5), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense0_bias (shape=(4,), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_weight (shape=(2, 4), dtype=<class 'numpy.float32'>)
  Parameter sequential1_dense1_bias (shape=(2,), dtype=<class 'numpy.float32'>)
)

In [20]:
net = nn.Sequential()
with net.name_scope():
    net.add(nn.Dense(4, activation='relu'))
    net.add(nn.Dense(4, activation='relu'))
    net.add(nn.Dense(4, activation='relu', params=net[-1].params))
    net.add(nn.Dense(2))

In [22]:
net.initialize()
net(x)
net[1].weight.data()

/Users/poodarchu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:320: UserWarning: Parameter sequential2_dense0_weight is already initialized, ignoring. Set force_reinit=True to re-initialize.
  "Set force_reinit=True to re-initialize."%self.name)
/Users/poodarchu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:320: UserWarning: Parameter sequential2_dense0_bias is already initialized, ignoring. Set force_reinit=True to re-initialize.
  "Set force_reinit=True to re-initialize."%self.name)
/Users/poodarchu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:320: UserWarning: Parameter sequential2_dense1_weight is already initialized, ignoring. Set force_reinit=True to re-initialize.
  "Set force_reinit=True to re-initialize."%self.name)
/Users/poodarchu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:320: UserWarning: Parameter sequential2_dense1_bias is already initialized, ignoring. Set force_reinit=True to re-initialize.
  "Set 


[[-0.00816047 -0.03040703  0.06714214 -0.05317248]
 [-0.01967777 -0.02854037 -0.00267491 -0.05337812]
 [ 0.02641256 -0.02548236  0.05326662 -0.01200318]
 [ 0.05855297 -0.06101935 -0.0396449   0.0269461 ]]
<NDArray 4x4 @cpu(0)>

In [24]:
# 自定义初始化, gluon 中 bias 都默认初始化为 0.
class MyInit(init.Initializer):
    def __init__(self):
        super(MyInit, self).__init__()
        self._verbose = True
    def _init_weight(self, _, arr):
        # 初始化权重，使用 out=arr 后不需要指定形状
        print('init weight', arr.shape)
        nd.random.uniform(low=5, high=10, out=arr)
net = get_net()
net.initialize(MyInit())
net[0].weight.data()
net(x)
net[0].weight.data()

DeferredInitializationError: Parameter sequential4_dense0_weight has not been initialized yet because initialization was deferred. Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.

In [26]:
# 可以通过 Parameter.set_data 来直接改写权重
# 由于存在 deferred initialization，可以使用 net(x) 先确定一下参数的形状
net = get_net()
net.initialize()
net(x)

params = net.collect_params()
print('default weight:', net[1].weight.data())
w2 = net[1].weight
w2.set_data(nd.ones(shape=w2.shape))
print('init to all 1s:', net[1].weight.data())

default weight: 
[[ 0.06699993  0.0279271  -0.05373173 -0.02835883]
 [ 0.03738332  0.0439317  -0.01234518 -0.0144892 ]]
<NDArray 2x4 @cpu(0)>
init to all 1s: 
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 2x4 @cpu(0)>


In [28]:
net.collect_params()
# net.params

sequential5_ (
  Parameter sequential5_dense0_weight (shape=(4, 5), dtype=<class 'numpy.float32'>)
  Parameter sequential5_dense0_bias (shape=(4,), dtype=<class 'numpy.float32'>)
  Parameter sequential5_dense1_weight (shape=(2, 4), dtype=<class 'numpy.float32'>)
  Parameter sequential5_dense1_bias (shape=(2,), dtype=<class 'numpy.float32'>)
)

In [29]:
net.params

sequential5_ (

)

In [30]:
type(net.params)

mxnet.gluon.parameter.ParameterDict

In [31]:
type(net.collect_params())

mxnet.gluon.parameter.ParameterDict