In [3]:
from mxnet import ndarray as nd

In [4]:
nd.zeros((3, 4))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.array([[1, 3], [2, 4]])


[[ 1.  3.]
 [ 2.  4.]]
<NDArray 2x2 @cpu(0)>

In [6]:
y = nd.random_normal(0, 2, shape=(3, 5))

In [7]:
y


[[ 2.32615733  0.96760923  0.59912694  0.30605093 -2.33762956]
 [ 3.11614227 -1.09188914 -4.71125937  1.08288038  5.35701323]
 [ 2.50926876 -1.09754789 -1.36212873 -0.27063167  0.75446254]]
<NDArray 3x5 @cpu(0)>

In [8]:
y.shape

(3, 5)

In [9]:
y.size

15

In [10]:
a = nd.arange(3).reshape((3, 1))

In [11]:
b = nd.arange(2).reshape((1, 2))

In [12]:
print (a)


[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>


In [13]:
print(b)


[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>


In [14]:
a+b


[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>

In [15]:
import numpy as np

In [16]:
x = np.ones((2, 3))

In [17]:
y = nd.array(x)
z = y.asnumpy()

In [18]:
print(x, y, z)

[[ 1.  1.  1.]
 [ 1.  1.  1.]] 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)> [[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [19]:
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
y


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>

In [21]:
z

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [23]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x+z
after = id(z)
print(before == after)

AssertionError: Argument data must have NDArray type, but got [[ 1.  1.  1.]
 [ 1.  1.  1.]]

In [24]:
x = nd.ones((3, 4))
y = nd.ones((3, 4))

before = id(y)
y = y + x
id(y) == before

False

In [25]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x+y
id(z) == before

True

In [26]:
nd.elemwise_add(x, y, out=z)


[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 3x4 @cpu(0)>

In [27]:
before = id(x)
x += y # or x[:] = x+y
id(x) == before

True

In [28]:
from mxnet import ndarray as nd
from mxnet import autograd as ag

In [30]:
x = nd.array([[1, 2], [3, 4]])

In [31]:
x.attach_grad()

In [32]:
with ag.record():
    y = x * 2
    z = y * x

In [33]:
z.backward()

In [34]:
x.grad == 4*x


[[ 1.  1.]
 [ 1.  1.]]
<NDArray 2x2 @cpu(0)>

In [35]:
print(z)


[[  2.   8.]
 [ 18.  32.]]
<NDArray 2x2 @cpu(0)>


In [36]:
def f(a):
    b = a*2
    while nd.norm(b).asscalar() < 1000:
        b = b*2
    if nd.sum(b).asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [37]:
a = nd.random_normal(3)

In [38]:
print (a)


3.4101643562316895
<NDArray  @cpu(0)>


In [39]:
a = nd.normal(shape=3)

In [40]:
print (a)


[ 0.5712682 -2.7579627  1.07628  ]
<NDArray 3 @cpu(0)>


In [41]:
a.attach_grad()

In [42]:
with ag.record():
    c = f(a)
c.backward()

In [43]:
print(a.grad)


[ 51200.  51200.  51200.]
<NDArray 3 @cpu(0)>


In [44]:
# 头梯度和链式法则
with ag.record():
    y = x * 2
    z = y * x
head_gradient = nd.array([[10, 1.], [.1, .01]])
z.backward(head_gradient)
print(y.grad)

None


In [45]:
print(x.grad)


[[ 40.           8.        ]
 [  1.20000005   0.16      ]]
<NDArray 2x2 @cpu(0)>
