In [9]:
from mxnet.gluon import nn
from mxnet import nd

In [10]:
x = nd.ones(3)
y = nd.zeros(4)
filename = './data/sequentialization.params'
nd.save(filename, [x, y])

In [11]:
a, b = nd.load(filename)

In [12]:
print(a, b)


[ 1.  1.  1.]
<NDArray 3 @cpu(0)> 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>


In [13]:
def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(10, activation="relu"))
        net.add(nn.Dense(2))
    return net

net = get_net()
net.initialize()
x = nd.random.uniform(shape=(2,10))
print(net(x))



[[ 0.00202203  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>


In [14]:
filename1 = './data/gluon_sequentialization.params'
net.save_params(filename1)

In [15]:
import mxnet as mx

net2 = get_net()
net2.load_params(filename1, mx.cpu())

In [ ]:
net2(x)