In [1]:
#　MXNet's NDArray enables imperative computation.
# MXNet's NDArray supports fast execution on a wide range of hardware configurations: CPU, GPU, multi-GPU and Cloud.
# MXNet's NDArray executes code lazily, allowing it to automatically multiple operations across the available hardware.

In [4]:
import mxnet as mx
import math

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

/home/poodar/Library/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:871: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
  EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
/home/poodar/Library/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  if d.decorator_argspec is not None), _inspect.getargspec(target))
/home/poodar/Library/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py:4422: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/poodar/.keras/keras.json' mode='r' encoding='UTF-8'>
  _config = json.load(open(_config_path))
/home/poodar/Library/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/poodar/Library/

In [6]:
a = mx.nd.array(np.arange(24))
b = a.reshape((2, 3, 4))
b.asnumpy()

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)

In [7]:
a = mx.nd.ones((3, 4))
b = mx.nd.sum(a)
b.asnumpy()

array([12.], dtype=float32)

In [8]:
a = mx.nd.array(np.arange(6).reshape(6, 1))
b = a.broadcast_to((6, 4))
b.asnumpy()

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]], dtype=float32)

In [10]:
c = a.reshape((2, 1, 1, 3))
d = c.broadcast_to((2, 2, 2, 3))
d.asnumpy()

array([[[[0., 1., 2.],
         [0., 1., 2.]],

        [[0., 1., 2.],
         [0., 1., 2.]]],


       [[[3., 4., 5.],
         [3., 4., 5.]],

        [[3., 4., 5.],
         [3., 4., 5.]]]], dtype=float32)

In [19]:
a = mx.nd.zeros((2, 2))
b = a.copy()

In [20]:
b is a

False

In [21]:
b = mx.nd.ones(a.shape)

In [22]:
c = b
c is b

True

In [23]:
b is c

True

In [24]:
c[:] = a
c is b

True

In [25]:
b


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

In [26]:
d = b

In [27]:
c is d

True

In [28]:
a.copyto(d)


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

In [29]:
d is b

True

In [30]:
gpu_device = mx.gpu()

In [31]:
def f():
    a = mx.nd.ones((100, 100))
    b = mx.nd.ones((100, 100))
    c = a + b
    print (c)

In [32]:
with mx.Context(mx.gpu()):
    f()


[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
<NDArray 100x100 @gpu(0)>


In [33]:
d = mx.nd.ones((10, 20), mx.gpu())

In [34]:
d


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 10x20 @gpu(0)>

In [35]:
e = mx.nd.zeros(d.shape)

In [36]:
e


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<NDArray 10x20 @cpu(0)>

In [37]:
d.copyto(e)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 10x20 @cpu(0)>

In [38]:
e


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 10x20 @cpu(0)>

In [39]:
d + e

MXNetError: [15:15:34] src/imperative/./imperative_utils.h:55: Check failed: inputs[i]->ctx().dev_mask() == ctx.dev_mask() (1 vs. 2) Operator broadcast_add require all inputs live on the same context. But the first argument is on gpu(0) while the 2-th argument is on cpu(0)

Stack trace returned 10 entries:
[bt] (0) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2a9e78) [0x7f7b4d02ae78]
[bt] (1) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2aa288) [0x7f7b4d02b288]
[bt] (2) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24b308c) [0x7f7b4f23408c]
[bt] (3) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x24c1bfe) [0x7f7b4f242bfe]
[bt] (4) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2403a7b) [0x7f7b4f184a7b]
[bt] (5) /home/poodar/Library/anaconda3/lib/python3.6/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x63) [0x7f7b4f184fe3]
[bt] (6) /home/poodar/Library/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f7b98e0bec0]
[bt] (7) /home/poodar/Library/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f7b98e0b87d]
[bt] (8) /home/poodar/Library/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f7b99020dee]
[bt] (9) /home/poodar/Library/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7f7b99021825]



In [40]:
f = e.as_in_context(d.context)

In [41]:
d + f


[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
<NDArray 10x20 @gpu(0)>

In [43]:
import pickle as pkl

In [44]:
a = mx.nd.ones((2, 3))
data = pkl.dumps(a)
pkl.dump(data, open('tmp.pickle', 'wb'))

/home/poodar/Library/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: ResourceWarning: unclosed file <_io.BufferedWriter name='tmp.pickle'>
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
ls

CS231n - Preparation 1 Python Numpy Tutorial.ipynb
Image Classification Data Driven Approach  kNN train val test splits.ipynb
Mask-RCNN/
MXNet-Introduction-Basics.ipynb
tf_custom_estimator.ipynb
tf_get_started.ipynb
tmp.pickle


In [46]:
data2 = pkl.load(open('tmp.pickle', 'rb'))
b = pkl.loads(data2)
b

/home/poodar/Library/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: ResourceWarning: unclosed file <_io.BufferedReader name='tmp.pickle'>
  """Entry point for launching an IPython kernel.



[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [47]:
# Lazy Evaluation and Automatic Parallelization

In [48]:
import time
def do(x, n):
    return [mx.nd.dot(x, x) for i in range(n)]
def wait(x):
    for i in x:
        i.wait_to_read()

In [49]:
tic = time.time()
a = mx.nd.ones((1000, 1000))
b = do(a, 50)
print('time for all computations are pushed into backend engin:\n %f sec' % (time.time()-tic))
wait(b)
print('time for all computations are finished:\n %f sec' %(time.time()-tic))

time for all computations are pushed into backend engin:
 0.001735 sec
time for all computations are finished:
 0.494016 sec


In [51]:
n = 10
a = mx.nd.ones((6000,6000))
b = mx.nd.ones((6000,6000), gpu_device)
tic = time.time()
c = do(a, n)
wait(c)
print('Time to finish the CPU workload: %f sec' % (time.time() - tic))
d = do(b, n)
wait(d)
print('Time to finish both CPU/GPU workloads: %f sec' % (time.time() - tic))

Time to finish the CPU workload: 17.840737 sec
Time to finish both CPU/GPU workloads: 18.794532 sec


In [52]:
# If we issue all workloads at the same time, the backend engine will try to parallel the CPU and GPU computations.
tic = time.time()
c = do(a, n)
d = do(b, n)
wait(c)
wait(d)
print('time to finish both CPU and GPU computations: %f sec' %(time.time() - tic))

time to finish both CPU and GPU computations: 17.750711 sec


# NDArray Indexing - Array indexing features

In [53]:
# Advanced indexing always returns a copy of the data.

In [54]:
x = mx.nd.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
], dtype='int32')
x[[0, 1, 2], [0, 1, 0]]


[1 4 5]
<NDArray 3 @cpu(0)>

In [55]:
# example: select the corner elements of an 4x3 array.
x = mx.nd.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
], dtype='int32')
x[
    [
        [0, 0], 
        [3, 3]
    ],
    [
        [0, 2], 
        [0, 2]
    ]
 ]


[[ 0  2]
 [ 9 11]]
<NDArray 2x2 @cpu(0)>

In [57]:
x[[[0], [3]],
  [[0, 2]]]


[[ 0  2]
 [ 9 11]]
<NDArray 2x2 @cpu(0)>

In [58]:
import numpy as np
shape = (10, 20, 30, 40, 50)
x = mx.nd.arange(np.prod(shape), dtype='int32').reshape(shape)
ind = mx.nd.arange(24).reshape((2, 3, 4))
print(x[:, :, ind].shape)

(10, 20, 2, 3, 4, 40, 50)


In [59]:
np.prod(shape)

12000000

In [60]:
x


[[[[[       0        1        2 ...       47       48       49]
    [      50       51       52 ...       97       98       99]
    [     100      101      102 ...      147      148      149]
    ...
    [    1850     1851     1852 ...     1897     1898     1899]
    [    1900     1901     1902 ...     1947     1948     1949]
    [    1950     1951     1952 ...     1997     1998     1999]]

   [[    2000     2001     2002 ...     2047     2048     2049]
    [    2050     2051     2052 ...     2097     2098     2099]
    [    2100     2101     2102 ...     2147     2148     2149]
    ...
    [    3850     3851     3852 ...     3897     3898     3899]
    [    3900     3901     3902 ...     3947     3948     3949]
    [    3950     3951     3952 ...     3997     3998     3999]]

   [[    4000     4001     4002 ...     4047     4048     4049]
    [    4050     4051     4052 ...     4097     4098     4099]
    [    4100     4101     4102 ...     4147     4148     4149]
    ...
    [    58

In [61]:
ind1 = [0, 1, 2, 3]
ind2 = [[[0], [1], [2]], [[3], [4], [5]]]
print(x[:, :, ind1, ind2, :].shape)

(10, 20, 2, 3, 4, 50)


In [62]:
print(x[:, :, ind1, :, ind2].shape)

(2, 3, 4, 10, 20, 40)
